export const userDataActions = {
  INITATE_LOGIN: "USER_DATA/INITATE_LOGIN",
  AUTHENTICATION_SUCCESS: "USER_DATA/AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAILED: "USER_DATA/AUTHENTICATION_FAILED",
  RESET_STATUS: "USER_DATA/RESET_STATUS",
};

export const contactActions = {
  FETCH_CONTACTS: "CONTACTS/FETCH_CONTACTS",
  FETCH_SUCCESS: "CONTACTS/FETCH_SUCCESS",
  FETCH_FAILED: "CONTACTS/FETCH_FAILED",
  RESET_CONTACTS: "CONTACTS/RESET_CONTACTS",
};

export const conversationActions = {
  FETCH_ALL_CONVERSATIONS: "CONVERSATIONS/FETCH_ALL_CONVERSATIONS",
  FETCH_ALL_CONVERSATIONS_SUCCESS:
    "CONVERSATIONS/FETCH_ALL_CONVERSATIONS_SUCCESS",
  FETCH_ALL_CONVERSATIONS_ERROR: "CONVERSATIONS/FETCH_ALL_CONVERSATIONS_ERROR",
  ADD_CONVERSATION: "CONVERSATIONS/ADD_CONVERSATION",
  DELETE_CONVERSATION: "CONVERSATIONS/DELETE_CONVERSATION",
  ADD_MESSAGE_TO_CONVERSATION: "CONVERSATIONS/ADD_MESSAGE_TO_CONVERSATION",
};
