export const userDataActions = {
  INITATE_LOGIN: "USER_DATA/INITATE_LOGIN",
  AUTHENTICATION_SUCCESS: "USER_DATA/AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAILED: "USER_DATA/AUTHENTICATION_FAILED",
  RESET_STATUS: "USER_DATA/RESET_STATUS",
  CREATE_SOCKET: "USER_DATA/CREATE_SOCKET",
  RESET_SOCKET: "USER_DATA/RESET_SOCKET",
  DISCONNECT_SOCKET: "USER_DATA/DISCONNECT_SOCKET",
};

export const contactActions = {
  FETCH_CONTACTS: "CONTACTS/FETCH_CONTACTS",
  FETCH_SUCCESS: "CONTACTS/FETCH_SUCCESS",
  FETCH_FAILED: "CONTACTS/FETCH_FAILED",
  RESET_CONTACTS: "CONTACTS/RESET_CONTACTS",
};

export const conversationActions = {
  FETCH_ALL_CONVERSATIONS: "CONVERSATIONS/FETCH_ALL_CONVERSATIONS",
  FETCH_ALL_CONVERSATIONS_SUCCESS:
    "CONVERSATIONS/FETCH_ALL_CONVERSATIONS_SUCCESS",
  FETCH_ALL_CONVERSATIONS_ERROR: "CONVERSATIONS/FETCH_ALL_CONVERSATIONS_ERROR",
  ADD_CONVERSATION: "CONVERSATIONS/ADD_CONVERSATION",
  CLEAR_ALL_CONVERSATIONS: "CONVERSATIONS/CLEAR_ALL_CONVERSATIONS",
  DELETE_CONVERSATION: "CONVERSATIONS/DELETE_CONVERSATION",
  ADD_MESSAGE_TO_CONVERSATION: "CONVERSATIONS/ADD_MESSAGE_TO_CONVERSATION",
};

export const notificationsActions = {
  ADD_NOTIFICATION: "NOTIFICATIONS/ADD_NOTIFICATION",
  DELETE_NOTIFICATION: "NOTIFICATIONS/DELETE_NOTIFICATION",
  CLEAR_ALL_NOTIFICATIONS: "NOTIFICATIONS/CLEAR_ALL_NOTIFICATIONS",
  ENABLE_NOTIFICATIONS: "NOTIFICATIONS/ENABLE_NOTIFICATIONS",
  DISABLE_NOTIFICATIONS: "NOTIFICATIONS/DISABLE_NOTIFICATIONS",
};
