export const userDataActions = {
  INITATE_LOGIN: "USER_DATA/INITATE_LOGIN",
  AUTHENTICATION_SUCCESS: "USER_DATA/AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAILED: "USER_DATA/AUTHENTICATION_FAILED",
  RESET_STATUS: "USER_DATA/RESET_STATUS",
};
